/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        white: "var(--white)",
        "low-opacity-black": "var(--low-opacity-black)",
        "slate-blue-gray": "var(--slate-blue-gray)",
        "slate-indigo": "var(--slate-indigo)",
        "golden-yellow": "var(--golden-yellow)",
        "misty-sky-blue": "var(--misty-sky-blue)",
        "light-blue": "var(--light-blue)",
        "medium-blue": "var(--medium-blue)",
        "dodger-blue": "var(--dodger-blue)",
        "powder-blue": "var(--powder-blue)",
        "pale-sky-blue": "var(--pale-sky-blue)",
        "sky-blue": "var(--sky-blue)",
        "whispering-sky-blue": "var(--whispering-sky-blue)",
        "royal-blue": "var(--royal-blue)",
        "vivid-blue": "var(--vivid-blue)",
        "dark-blue": "var(--dark-blue)",
        "oceanic-blue": "var(--oceanic-blue)",
      },
      fontSize: {
        // Define fontSizes here
        132: "132px",
        92: "92px",
        82: "82px",
        72: "72px",
        64: "64px",
        48: "48px",
        36: "36px",
        32: "32px",
        30: "30px",
        27: "27px",
        24: "24px",
        22: "22px",
        20: "20px",
        19: "19px",
        17: "17px",
        18: "18px",
        16: "16px",
        15: "15px",
        14: "14px",
        13: "13px",
        12: "12px",
        11: "11px",
      },
      borderWidth: {
        1: "1px",
      },
    },
  },
  plugins: [],
};
